# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326c13121f7e612d096160ad576cdf0f157daea30af1e2943394c5c7e032d1723a69055f170d3fa451dc8a89c9d27a6249cf56ceb7d0ab4846413d74e48816b3

test:
  secret_key_base: 39ae6b9dbd124bb49a8fa15ee1ca1f76e57d4ca40df070ba13321041eae96ce0a1082511c4c8829983e21fadae318ffa7b9447f43cf0459b1a3c28b14af5836c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
